<?php
require_once __DIR__ . '/phase2.php';
p2_start();
$pdo = p2_db();
$metrics = [
    'Active clients' => (int)$pdo->query("SELECT COUNT(*) FROM p2_clients")->fetchColumn(),
    'Open matters' => (int)$pdo->query("SELECT COUNT(*) FROM p2_matters WHERE status != 'closed'")->fetchColumn(),
    'Open tasks' => (int)$pdo->query("SELECT COUNT(*) FROM p3_tasks WHERE status='open'")->fetchColumn(),
    'Upcoming deadlines' => (int)$pdo->query("SELECT COUNT(*) FROM p2_deadlines WHERE status='open' AND due_on BETWEEN date('now') AND date('now','+7 days')")->fetchColumn(),
    'Pending responses' => (int)$pdo->query("SELECT COUNT(*) FROM p5_correspondence c WHERE direction='incoming' AND requires_response=1 AND NOT EXISTS (SELECT 1 FROM p5_correspondence reply JOIN draft_letters reply_letter ON reply_letter.id=reply.letter_id WHERE reply.reply_to_letter_id=c.letter_id AND reply_letter.status='sent')")->fetchColumn(),
];
$overdue = (int)$pdo->query("SELECT COUNT(*) FROM p2_deadlines WHERE status='open' AND due_on < date('now')")->fetchColumn();
$due = $pdo->query("SELECT d.*, m.reference, m.title AS matter_title FROM p2_deadlines d LEFT JOIN p2_matters m ON m.id=d.matter_id WHERE d.status='open' ORDER BY d.due_on LIMIT 5")->fetchAll();
$activity = $pdo->query("SELECT a.*, m.reference, m.title AS matter_title FROM p2_activity a LEFT JOIN p2_matters m ON m.id=a.matter_id ORDER BY a.created_at DESC LIMIT 5")->fetchAll();
$matters = $pdo->query("SELECT m.*, c.name client_name,
    COALESCE((SELECT MAX(a.created_at) FROM p2_activity a WHERE a.matter_id=m.id), m.created_at) AS last_updated
    FROM p2_matters m LEFT JOIN p2_clients c ON c.id=m.client_id
    ORDER BY last_updated DESC, m.id DESC LIMIT 5")->fetchAll();
$p3_actions = $pdo->query("SELECT a.*, m.reference FROM p3_counsel_actions a LEFT JOIN p2_matters m ON m.id=a.matter_id WHERE a.status='open' ORDER BY COALESCE(a.due_on, '9999-12-31'), a.created_at DESC LIMIT 5")->fetchAll();
$recentLetters = $pdo->query("SELECT l.id,l.ref_no,l.subject,l.status,l.created_at,c.direction,c.requires_response,c.response_due_on,m.reference
    FROM draft_letters l LEFT JOIN p5_correspondence c ON c.letter_id=l.id
    LEFT JOIN p2_matters m ON m.id=c.matter_id ORDER BY l.created_at DESC,l.id DESC LIMIT 5")->fetchAll();
$responseQueue = $pdo->query("SELECT l.id,l.ref_no,l.subject,c.direction,c.response_due_on,m.reference
    FROM draft_letters l JOIN p5_correspondence c ON c.letter_id=l.id LEFT JOIN p2_matters m ON m.id=c.matter_id
    WHERE (c.direction='incoming' AND c.requires_response=1 AND NOT EXISTS (SELECT 1 FROM p5_correspondence reply JOIN draft_letters reply_letter ON reply_letter.id=reply.letter_id WHERE reply.reply_to_letter_id=c.letter_id AND reply_letter.status='sent')) OR (c.direction='outgoing' AND l.status='sent' AND c.requires_response=1 AND c.response_received_on IS NULL) ORDER BY CASE WHEN c.response_due_on IS NULL THEN 1 ELSE 0 END,c.response_due_on,l.created_at DESC LIMIT 5")->fetchAll();
$recentAiAnalysis = $pdo->query("SELECT s.workflow,s.created_at,m.id AS matter_id,m.reference,m.title FROM p6_ai_sessions s JOIN p2_matters m ON m.id=s.matter_id ORDER BY s.created_at DESC,s.id DESC LIMIT 5")->fetchAll();
$aiDrafts = $pdo->query("SELECT o.id,o.title,o.workflow,o.created_at,m.id AS matter_id,m.reference FROM p6_ai_outputs o JOIN p2_matters m ON m.id=o.matter_id ORDER BY o.created_at DESC,o.id DESC LIMIT 5")->fetchAll();
$riskAlerts = $pdo->query("SELECT r.title,r.likelihood,r.impact,m.id AS matter_id,m.reference FROM p4_workbench_risks r JOIN p2_matters m ON m.id=r.matter_id WHERE r.status='open' AND (r.likelihood='high' OR r.impact='high') ORDER BY CASE r.impact WHEN 'high' THEN 0 ELSE 1 END,r.id DESC LIMIT 5")->fetchAll();
$strategyReports = $pdo->query("SELECT o.title,o.created_at,m.id AS matter_id,m.reference FROM p6_ai_outputs o JOIN p2_matters m ON m.id=o.matter_id WHERE o.workflow IN ('advice','skeleton','appeal') ORDER BY o.created_at DESC,o.id DESC LIMIT 5")->fetchAll();
p2_page('Dashboard', 'dashboard.php', function () use ($metrics, $overdue, $due, $activity, $matters, $p3_actions, $recentLetters, $responseQueue, $recentAiAnalysis, $aiDrafts, $riskAlerts, $strategyReports) { ?>
<div class="toolbar"><div><h1><?= (int)date('G') < 12 ? 'Good morning' : ((int)date('G') < 18 ? 'Good afternoon' : 'Good evening') ?>, <?= p2_h($_SESSION['full_name'] ?? $_SESSION['username'] ?? 'Counsel') ?></h1><p class="subhead"><?= date('l, j F Y') ?> · <?= $overdue ? $overdue . ' overdue deadline' . ($overdue === 1 ? '' : 's') . ' need attention.' : 'No overdue deadlines. Your workspace is up to date.' ?></p></div><div><a class="button" href="matters.php?action=new">+ New matter</a> <a class="button secondary" href="counsel_engine.php">Open Counsel Engine</a></div></div>
<section class="grid grid-4"><?php foreach ($metrics as $label => $value): ?><div class="card"><div class="metric"><?= $value ?></div><div class="metric-label"><?= p2_h($label) ?></div></div><?php endforeach; ?></section>
<section class="quick-actions" aria-label="Quick actions"><a href="clients.php">Add client</a><a href="documents.php">Link document</a><a href="deadlines.php">Review deadlines</a><a href="knowledge_centre.php">Knowledge Centre</a><a href="reports.php">View reports</a></section>
<section class="grid grid-2 dashboard-grid" style="margin-top:18px">
 <div class="card"><div class="split"><h2>Recent matters</h2><a class="small" href="matters.php">View all</a></div><?php if (!$matters): ?><div class="empty">Your matter list is ready when you are.<br><a href="matters.php?action=new">Create your first matter</a> to connect client work, documents and deadlines.</div><?php else: ?><table><thead><tr><th>Reference</th><th>Client</th><th>Status</th><th>Last update</th></tr></thead><tbody><?php foreach ($matters as $matter): ?><tr><td><a href="matters.php?id=<?= $matter['id'] ?>"><?= p2_h($matter['reference'] ?: $matter['title']) ?></a></td><td><?= p2_h($matter['client_name'] ?: 'Unassigned') ?></td><td><?= p2_status_badge($matter['status']) ?></td><td><?= p2_h(date('d M Y', strtotime($matter['last_updated']))) ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Upcoming deadlines</h2><a class="small" href="deadlines.php">View all</a></div><?php if (!$due): ?><div class="empty">Nothing is due yet.<br>Add dates from a matter workspace to keep important obligations visible here.</div><?php else: ?><ul class="compact-list"><?php foreach ($due as $item): ?><li><span><strong><?= p2_h($item['title']) ?></strong><small><a href="matters.php?id=<?= $item['matter_id'] ?>"><?= p2_h($item['reference'] ?: $item['matter_title'] ?: 'General') ?></a> · <?= p2_h($item['due_on']) ?></small></span><?= p2_due_badge($item['due_on']) ?></li><?php endforeach; ?></ul><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Recent activity</h2><a class="small" href="reports.php">View reports</a></div><?php if (!$activity): ?><div class="empty">Activity will appear as work is created, edited, analysed, researched or completed.</div><?php else: ?><ol class="activity-stream"><?php foreach ($activity as $event): ?><li><strong><?= p2_h(p2_event_label($event['event_type'])) ?></strong><span><?= p2_h($event['description']) ?><?= $event['reference'] ? ' · ' . p2_h($event['reference']) : '' ?> · <?= p2_h(date('d M H:i', strtotime($event['created_at']))) ?></span></li><?php endforeach; ?></ol><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Counsel actions</h2><a class="small" href="counsel_engine.php">Open workspace</a></div><?php if (!$p3_actions): ?><div class="empty">No outstanding counsel actions.<br>Run an inline Counsel Engine review from a matter when a legal question needs a structured next step.</div><?php else: ?><ul class="compact-list"><?php foreach ($p3_actions as $action): ?><li><a href="counsel_engine.php?matter_id=<?= $action['matter_id'] ?>"><?= p2_h($action['title']) ?><small><?= p2_h($action['reference'] ?: 'General') ?></small></a><?= $action['due_on'] ? p2_due_badge($action['due_on']) : p2_status_badge('open') ?></li><?php endforeach; ?></ul><?php endif; ?></div>
</section>
<section class="grid grid-2 dashboard-grid" style="margin-top:18px">
 <div class="card"><div class="split"><h2>Recent correspondence</h2><a class="small" href="letter_list.php">Open workbench</a></div><?php if (!$recentLetters): ?><div class="empty">No correspondence has been saved yet.<br><a href="letter_create.php">Draft a letter</a> to begin the record.</div><?php else: ?><ul class="compact-list"><?php foreach ($recentLetters as $letter): ?><li><span><a href="letter_view.php?id=<?= $letter['id'] ?>"><strong><?= p2_h($letter['ref_no'] ?: 'Unreferenced') ?></strong></a><small><?= p2_h($letter['subject']) ?> · <?= p2_h($letter['reference'] ?: 'Unlinked') ?></small></span><?= p2_status_badge($letter['status']) ?></li><?php endforeach; ?></ul><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Pending responses &amp; awaiting replies</h2><a class="small" href="letter_list.php">Review queue</a></div><?php if (!$responseQueue): ?><div class="empty">No response commitments are awaiting action.</div><?php else: ?><ul class="compact-list"><?php foreach ($responseQueue as $letter): ?><li><span><a href="letter_view.php?id=<?= $letter['id'] ?>"><strong><?= p2_h($letter['ref_no'] ?: 'Unreferenced') ?></strong></a><small><?= $letter['direction']==='incoming' ? 'Response to prepare' : 'Reply awaited' ?><?= $letter['response_due_on'] ? ' · due ' . p2_h($letter['response_due_on']) : '' ?></small></span><a class="button secondary" href="letter_view.php?id=<?= $letter['id'] ?>">Open</a></li><?php endforeach; ?></ul><?php endif; ?></div>
</section>
<section class="grid grid-2 dashboard-grid" style="margin-top:18px">
 <div class="card"><div class="split"><h2>Recent AI analysis</h2><a class="small" href="counsel_engine.php">Counsel Engine</a></div><?php if (!$recentAiAnalysis): ?><div class="empty">No local AI analysis has been run. Open a matter to start a preliminary, reviewable workflow.</div><?php else: ?><ul class="compact-list"><?php foreach ($recentAiAnalysis as $item): ?><li><span><a href="counsel_engine.php?matter_id=<?= (int)$item['matter_id'] ?>#ai-workflows"><strong><?= p2_h(p6_workflows()[$item['workflow']] ?? $item['workflow']) ?></strong></a><small><?= p2_h($item['reference']) ?> · <?= p2_h(date('d M H:i', strtotime($item['created_at']))) ?></small></span><span class="badge badge-draft">Preliminary</span></li><?php endforeach; ?></ul><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Recent AI drafts</h2><a class="small" href="documents.php">Document library</a></div><?php if (!$aiDrafts): ?><div class="empty">Generated drafts will be saved to their client matter and document library.</div><?php else: ?><ul class="compact-list"><?php foreach ($aiDrafts as $item): ?><li><span><a href="counsel_engine.php?matter_id=<?= (int)$item['matter_id'] ?>#ai-workflows"><strong><?= p2_h($item['title']) ?></strong></a><small><?= p2_h($item['reference']) ?> · <?= p2_h(date('d M H:i', strtotime($item['created_at']))) ?></small></span><span class="badge badge-draft">Draft</span></li><?php endforeach; ?></ul><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Risk alerts</h2><a class="small" href="counsel_engine.php">Review risks</a></div><?php if (!$riskAlerts): ?><div class="empty">No high likelihood or high impact matter risks are open.</div><?php else: ?><ul class="compact-list"><?php foreach ($riskAlerts as $item): ?><li><span><a href="counsel_engine.php?matter_id=<?= (int)$item['matter_id'] ?>"><strong><?= p2_h($item['title']) ?></strong></a><small><?= p2_h($item['reference']) ?> · <?= p2_h($item['likelihood']) ?> likelihood / <?= p2_h($item['impact']) ?> impact</small></span><span class="badge badge-high">Review</span></li><?php endforeach; ?></ul><?php endif; ?></div>
 <div class="card"><div class="split"><h2>Strategy reports</h2><a class="small" href="counsel_engine.php">Generate report</a></div><?php if (!$strategyReports): ?><div class="empty">Create advice, appeal or skeleton workflows to retain strategy reports against a matter.</div><?php else: ?><ul class="compact-list"><?php foreach ($strategyReports as $item): ?><li><span><a href="counsel_engine.php?matter_id=<?= (int)$item['matter_id'] ?>#ai-workflows"><strong><?= p2_h($item['title']) ?></strong></a><small><?= p2_h($item['reference']) ?> · <?= p2_h(date('d M Y', strtotime($item['created_at']))) ?></small></span><span class="badge badge-open">Strategy</span></li><?php endforeach; ?></ul><?php endif; ?></div>
</section>
<section class="card" style="margin-top:18px"><h2>Existing document tools</h2><p class="small">Connected workspaces complement the established drafting modules.</p><div class="toolbar" style="margin:12px 0 0"><a class="button secondary" href="advice_list.php">Legal advice</a><a class="button secondary" href="letter_list.php">Letters</a><a class="button secondary" href="witness_list.php">Witness statements</a><a class="button secondary" href="skeleton_list.php">Skeleton arguments</a><a class="button secondary" href="appeal_list.php">Appeals</a></div></section>
<?php }); ?>
