<?php
require_once __DIR__ . '/phase2.php'; p2_start(); $pdo=p2_db(); p2_check_csrf();
if($_SERVER['REQUEST_METHOD']==='POST'){
    $title=trim($_POST['title']??''); $matter=(int)($_POST['matter_id']??0);
    if(!$title || !$matter) p2_redirect('documents.php','Select a matter and enter a document title.');
    $stmt=$pdo->prepare('INSERT INTO p2_documents (matter_id,title,document_type,source_table,source_id,content,created_by) VALUES (?,?,?,?,?,?,?)');
    $stmt->execute([$matter,$title,trim($_POST['document_type']??'note'),trim($_POST['source_table']??'')?:null,(int)($_POST['source_id']??0)?:null,trim($_POST['content']??''),p2_user_id()]);
    $id=(int)$pdo->lastInsertId(); $pdo->prepare('INSERT INTO p2_document_links (document_id,matter_id) VALUES (?,?)')->execute([$id,$matter]); p2_log('document.linked',"Linked document: $title",$matter,['document_id'=>$id,'source_table'=>$_POST['source_table']??null,'source_id'=>$_POST['source_id']??null]); p2_redirect("matters.php?id=$matter",'Document linked to matter.');
}
$matters=p2_matter_options($pdo);$selected=(int)($_GET['matter_id']??0);
$documents=$pdo->query('SELECT d.*,m.reference,m.title matter_title FROM p2_documents d LEFT JOIN p2_matters m ON m.id=d.matter_id ORDER BY d.created_at DESC LIMIT 100')->fetchAll();
p2_page('Documents','documents.php',function()use($matters,$selected,$documents){ ?>
<div class="toolbar"><div><h1>Document linking</h1><p class="subhead">Link notes and existing platform records to the correct matter workspace.</p></div></div>
<div class="grid grid-2"><section class="card"><h2>Link a document</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=p2_csrf()?>"><div class="full"><label>Matter *</label><select required name="matter_id"><option value="">Select matter</option><?php foreach($matters as $m):?><option value="<?=$m['id']?>" <?=$selected===$m['id']?'selected':''?>><?=p2_h($m['reference'].' — '.$m['title'])?></option><?php endforeach;?></select></div><div><label>Document type</label><select name="document_type"><option value="note">Matter note</option><option value="advice">Legal advice</option><option value="letter">Letter</option><option value="evidence">Evidence</option><option value="filing">Court filing</option></select></div><div><label>Title *</label><input required name="title"></div><div><label>Existing record table (optional)</label><input name="source_table" placeholder="e.g. legal_advice"></div><div><label>Existing record ID (optional)</label><input type="number" min="1" name="source_id"></div><div class="full"><label>Summary / note</label><textarea name="content" placeholder="Why this document belongs on the matter or a concise document summary"></textarea></div><div><button>Link document</button></div></form></section>
<section class="card"><h2>Linked documents</h2><?php if(!$documents):?><div class="empty">No documents have been linked.</div><?php else:?><table><thead><tr><th>Document</th><th>Matter</th><th>Source</th><th>Added</th></tr></thead><tbody><?php foreach($documents as $d):?><tr><td><?=p2_h($d['title'])?><br><span class="small"><?=p2_h($d['document_type'])?></span></td><td><a href="matters.php?id=<?=$d['matter_id']?>"><?=p2_h($d['reference']?:$d['matter_title'])?></a></td><td><?=p2_h($d['source_table'] ? $d['source_table'].' #'.$d['source_id'] : 'Workspace')?></td><td><?=p2_h(date('d M Y',strtotime($d['created_at'])))?></td></tr><?php endforeach;?></tbody></table><?php endif;?></section></div>
<?php }); ?>
